title: Notes
theme: just-the-docs

url: https://aderakin.github.io

compress_html:
  blanklines: true

# LaTeX rendering via "katex" (KaTeX, default) or "mathjax" (MathJax) or "none" / "off" (NO rendering)
latex: katex

enable_copy_code_button: true

